/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph9_MS2;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Four Lugtu
 */
public class FinanceDashboard extends javax.swing.JFrame {
    private Timer timer;
    private FinanceUser financeUser;

    /**
     * Creates new form FinanceDashboards
     */
    public FinanceDashboard() {
        initComponents();
    }
    
    public FinanceDashboard(User user) {
    
    }
    
    public FinanceDashboard(FinanceUser financeUser) {  // ✅ Pass FinanceUser object directly
        this.financeUser = financeUser; // ✅ Assign finance correctly
        initComponents(); // Call initComponents() to initialize UI
        setLocationRelativeTo(null); // Center the window
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Define close behavior
        startClock();

        // ✅ Debugging: Print ITUser details
        System.out.println("FinanceUser Data: ");
        System.out.println("Username: " + financeUser.getUsername());
        System.out.println("First Name: " + financeUser.getFirstName());
        System.out.println("Last Name: " + financeUser.getLastName());

        jLabelGreet.setText("Welcome, " + financeUser.getFirstName() + "!");
    }
    
    private void startClock() {
        timer = new Timer(1000, e -> updateTimeAndDate());
        timer.start();
    }
    
    private void updateTimeAndDate() {
        SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm:ss a");
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, MMMM d, yyyy");
        jLabelTime.setText(timeFormat.format(new Date()));
        jLabelDate.setText(dateFormat.format(new Date()));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelSeparate = new javax.swing.JLabel();
        jLabelGreet = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLblUname1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelFinanceGenRep1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGenRep = new javax.swing.JTable();
        jLabelGenRep2 = new javax.swing.JLabel();
        jPanelFinanceGenRep = new javax.swing.JPanel();
        jLabelReportNetSal = new javax.swing.JLabel();
        jLabelReportBasSal = new javax.swing.JLabel();
        jLabelReportTotDed = new javax.swing.JLabel();
        jLabelReportTotAll = new javax.swing.JLabel();
        jTextFieldReportNetSal = new javax.swing.JTextField();
        jTextFieldReportBasSal = new javax.swing.JTextField();
        jTextFieldReportTotAll = new javax.swing.JTextField();
        jTextFieldReportTotDed = new javax.swing.JTextField();
        jPanelFinanceGenRepHead = new javax.swing.JPanel();
        jLabelSelectDates1 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabelEmpNum3 = new javax.swing.JLabel();
        jTextFieldEmpNum2 = new javax.swing.JTextField();
        jButtonEmpNum2 = new javax.swing.JButton();
        jButtonGenPDF = new javax.swing.JButton();
        jButtonGenRep = new javax.swing.JButton();
        jButtonProcPay = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jLabelTime = new javax.swing.JLabel();
        jLabelGMT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(0, 0, 0));
        jPanelHeader.setForeground(new java.awt.Color(255, 102, 102));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSeparate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos9/horizontal (2).png"))); // NOI18N
        jLabelSeparate.setText("jLabel8");
        jPanelHeader.add(jLabelSeparate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 51, 404, 1));

        jLabelGreet.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabelGreet.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGreet.setText("Welcome!");
        jPanelHeader.add(jLabelGreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, -1));

        jLabelDate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate.setText("Wednesday, December 25, 2012");
        jLabelDate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanelHeader.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, -1, -1));

        jLblUname1.setBackground(new java.awt.Color(0, 0, 102));
        jLblUname1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLblUname1.setForeground(new java.awt.Color(255, 255, 255));
        jLblUname1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos9/LogoMPH_(small1).png"))); // NOI18N
        jLblUname1.setText("Username");
        jPanelHeader.add(jLblUname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 100, 110));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MOTOR");
        jPanelHeader.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -10, -1, 100));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("PH");
        jPanelHeader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -20, 70, 120));

        jPanel1.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 90));

        jPanelFinanceGenRep1.setBackground(new java.awt.Color(102, 0, 0));
        jPanelFinanceGenRep1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableGenRep.setBackground(new java.awt.Color(255, 255, 255));
        jTableGenRep.setForeground(new java.awt.Color(0, 0, 0));
        jTableGenRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableGenRep);

        jPanelFinanceGenRep1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1060, 340));

        jLabelGenRep2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelGenRep2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenRep2.setText("GENERATED REPORTS");
        jPanelFinanceGenRep1.add(jLabelGenRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, 40));

        jPanel1.add(jPanelFinanceGenRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 1080, 460));

        jPanelFinanceGenRep.setBackground(new java.awt.Color(102, 0, 0));
        jPanelFinanceGenRep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelReportNetSal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelReportNetSal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReportNetSal.setText("NET SALARY:");
        jPanelFinanceGenRep.add(jLabelReportNetSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, 50));

        jLabelReportBasSal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelReportBasSal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReportBasSal.setText("BASIC SALARY:");
        jPanelFinanceGenRep.add(jLabelReportBasSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 50));

        jLabelReportTotDed.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelReportTotDed.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReportTotDed.setText("TOTAL DEDUCTIONS:");
        jPanelFinanceGenRep.add(jLabelReportTotDed, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, 50));

        jLabelReportTotAll.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelReportTotAll.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReportTotAll.setText(" TOTAL ALLOWANCES:");
        jPanelFinanceGenRep.add(jLabelReportTotAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 50));

        jTextFieldReportNetSal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldReportNetSal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldReportNetSal.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFinanceGenRep.add(jTextFieldReportNetSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 140, 30));

        jTextFieldReportBasSal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldReportBasSal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldReportBasSal.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFinanceGenRep.add(jTextFieldReportBasSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, 30));

        jTextFieldReportTotAll.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldReportTotAll.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldReportTotAll.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFinanceGenRep.add(jTextFieldReportTotAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 140, 30));

        jTextFieldReportTotDed.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldReportTotDed.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldReportTotDed.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFinanceGenRep.add(jTextFieldReportTotDed, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 140, 30));

        jPanel1.add(jPanelFinanceGenRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 1080, 110));

        jPanelFinanceGenRepHead.setBackground(new java.awt.Color(102, 0, 0));
        jPanelFinanceGenRepHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSelectDates1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelSelectDates1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSelectDates1.setText("Select Date:");
        jPanelFinanceGenRepHead.add(jLabelSelectDates1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 50));

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFinanceGenRepHead.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 22, 190, 30));

        jLabelEmpNum3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelEmpNum3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpNum3.setText("Enter Employee Number:");
        jPanelFinanceGenRepHead.add(jLabelEmpNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jTextFieldEmpNum2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpNum2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextFieldEmpNum2.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFinanceGenRepHead.add(jTextFieldEmpNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 140, 30));

        jButtonEmpNum2.setBackground(new java.awt.Color(251, 0, 54));
        jButtonEmpNum2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonEmpNum2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmpNum2.setText("LOAD EMPLOYEE");
        jPanelFinanceGenRepHead.add(jButtonEmpNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 130, 30));

        jPanel1.add(jPanelFinanceGenRepHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 1080, 60));

        jButtonGenPDF.setBackground(new java.awt.Color(251, 0, 54));
        jButtonGenPDF.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonGenPDF.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenPDF.setText("Generate PDF");
        jPanel1.add(jButtonGenPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 40));

        jButtonGenRep.setBackground(new java.awt.Color(251, 0, 54));
        jButtonGenRep.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonGenRep.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenRep.setText("Generate Report");
        jPanel1.add(jButtonGenRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 40));

        jButtonProcPay.setBackground(new java.awt.Color(251, 0, 54));
        jButtonProcPay.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonProcPay.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProcPay.setText("Process Payroll");
        jPanel1.add(jButtonProcPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, 40));

        jButtonLogout.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 200, 30));

        jLabelTime.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTime.setText("12:12:12 AM");
        jPanel1.add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 210, 32));

        jLabelGMT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelGMT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGMT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGMT.setText("GMT+8 PH Time");
        jPanel1.add(jLabelGMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        Login newClassInstance = new Login();
        newClassInstance.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmpNum2;
    private javax.swing.JButton jButtonGenPDF;
    private javax.swing.JButton jButtonGenRep;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonProcPay;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelEmpNum3;
    private javax.swing.JLabel jLabelGMT;
    private javax.swing.JLabel jLabelGenRep2;
    private javax.swing.JLabel jLabelGreet;
    private javax.swing.JLabel jLabelReportBasSal;
    private javax.swing.JLabel jLabelReportNetSal;
    private javax.swing.JLabel jLabelReportTotAll;
    private javax.swing.JLabel jLabelReportTotDed;
    private javax.swing.JLabel jLabelSelectDates1;
    private javax.swing.JLabel jLabelSeparate;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLblUname1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFinanceGenRep;
    private javax.swing.JPanel jPanelFinanceGenRep1;
    private javax.swing.JPanel jPanelFinanceGenRepHead;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGenRep;
    private javax.swing.JTextField jTextFieldEmpNum2;
    private javax.swing.JTextField jTextFieldReportBasSal;
    private javax.swing.JTextField jTextFieldReportNetSal;
    private javax.swing.JTextField jTextFieldReportTotAll;
    private javax.swing.JTextField jTextFieldReportTotDed;
    // End of variables declaration//GEN-END:variables
}
