/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph_GUI;

import data_reader9.EmployeeDetailsReader;
import data_reader9.PasswordResetReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import data_reader9.PasswordResetReader;
import javax.swing.Timer;
import motorph9.PasswordResetRequest;
import motorph9.PasswordResetRequest;

/**
 *
 * @author Four Lugtu
 */

/**
 * Forgot Password Form - Handles password reset requests.
 * 
 * Uses `EmployeeDetailsReader` to validate Employee ID & Name before submission.
 * Ensures Employee Number contains **only numbers** and is **5 digits**.
 * Ensures Employee Name contains **only letters & spaces**.
 * Saves the request if all validations pass.
 */
public class ForgotPasswordForm extends javax.swing.JFrame {
    private Timer timer;
    private EmployeeDetailsReader employeeReader = new EmployeeDetailsReader();
    
    /**
     * Creates new form ForgotPasswordForm
     */
    
    public ForgotPasswordForm() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
        restrictDateChooser(); 
        startClock();
    }
    
    private void startClock() {
        timer = new Timer(1000, e -> updateTimeAndDate());
        timer.start();
    }

    private void updateTimeAndDate() {
        SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm:ss a");
        //SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, MMMM d, yyyy");
        jLabelTime.setText(timeFormat.format(new Date()));
        //jLabelDate.setText(dateFormat.format(new Date()));
    }
    
    /**
     * Restricts jDateChooser to **only allow today's date** (prevents past & future selections).
     */
    private void restrictDateChooser() {
        Date today = new Date();
        jDateChooser.setDate(today);
        jDateChooser.setMinSelectableDate(today);
        jDateChooser.setMaxSelectableDate(today);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanelForgotPassword = new javax.swing.JPanel();
        jPanelForgotPasswordLabel = new javax.swing.JPanel();
        jLabelForgotPassword = new javax.swing.JLabel();
        jPanelFormContents = new javax.swing.JPanel();
        jLabelFPEmpName = new javax.swing.JLabel();
        jTextFieldFPEmpName = new javax.swing.JTextField();
        jLabelFPEmpNum = new javax.swing.JLabel();
        jTextFieldFPEmpNum = new javax.swing.JTextField();
        jLabelFPDOR = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jPanelHeader = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabelMotor = new javax.swing.JLabel();
        jLabelPH = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelGMT = new javax.swing.JLabel();
        jButtonFPSubmit = new javax.swing.JButton();
        jButtonFPCancel = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelForgotPassword.setBackground(new java.awt.Color(51, 0, 0));
        jPanelForgotPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelForgotPasswordLabel.setBackground(new java.awt.Color(153, 0, 0));
        jPanelForgotPasswordLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelForgotPassword.setBackground(new java.awt.Color(255, 255, 255));
        jLabelForgotPassword.setFont(new java.awt.Font("Century Gothic", 1, 25)); // NOI18N
        jLabelForgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelForgotPassword.setText("EMPLOYEE FORGOT PASSWORD FORM");
        jPanelForgotPasswordLabel.add(jLabelForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 40));

        jPanelForgotPassword.add(jPanelForgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 470, 60));

        jPanelFormContents.setBackground(new java.awt.Color(153, 0, 0));
        jPanelFormContents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFPEmpName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpName.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jLabelFPEmpName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpName.setText("Employee Name:");
        jPanelFormContents.add(jLabelFPEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        jTextFieldFPEmpName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFPEmpName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFPEmpNameKeyTyped(evt);
            }
        });
        jPanelFormContents.add(jTextFieldFPEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 260, 30));

        jLabelFPEmpNum.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpNum.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jLabelFPEmpNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpNum.setText(" Employee Number:");
        jPanelFormContents.add(jLabelFPEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 70));

        jTextFieldFPEmpNum.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFPEmpNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFPEmpNumKeyTyped(evt);
            }
        });
        jPanelFormContents.add(jTextFieldFPEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 260, 30));

        jLabelFPDOR.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFPDOR.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jLabelFPDOR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFPDOR.setText("  Date of Request:");
        jPanelFormContents.add(jLabelFPDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 50));

        jDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFormContents.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 260, 30));

        jPanelForgotPassword.add(jPanelFormContents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 470, 140));

        jPanelHeader.setBackground(new java.awt.Color(0, 0, 0));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setBackground(new java.awt.Color(0, 0, 102));
        Logo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos9/LogoMPH_(small1).png"))); // NOI18N
        Logo.setText("Username");
        jPanelHeader.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 110));

        jLabelMotor.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelMotor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMotor.setText("MOTOR");
        jPanelHeader.add(jLabelMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 100));

        jLabelPH.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelPH.setForeground(new java.awt.Color(204, 0, 51));
        jLabelPH.setText("PH");
        jPanelHeader.add(jLabelPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, 70, 120));

        jLabelTime.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTime.setText("12:12:12 AM");
        jPanelHeader.add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 170, 32));

        jLabelGMT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelGMT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGMT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGMT.setText("GMT+8 PH Time");
        jPanelHeader.add(jLabelGMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 170, -1));

        jPanelForgotPassword.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 530, 100));

        jButtonFPSubmit.setBackground(new java.awt.Color(251, 0, 54));
        jButtonFPSubmit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonFPSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFPSubmit.setText("SUBMIT");
        jButtonFPSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFPSubmitActionPerformed(evt);
            }
        });
        jPanelForgotPassword.add(jButtonFPSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 170, 40));

        jButtonFPCancel.setBackground(new java.awt.Color(251, 0, 54));
        jButtonFPCancel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonFPCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFPCancel.setText("CANCEL");
        jButtonFPCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFPCancelActionPerformed(evt);
            }
        });
        jPanelForgotPassword.add(jButtonFPCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 170, 40));

        getContentPane().add(jPanelForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButtonFPSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFPSubmitActionPerformed
        /**
        * Handles Forgot Password submission.
        *   Validates Employee ID & Name before allowing submission.
        *   Saves request if validation is successful.
        */
        String empNum = jTextFieldFPEmpNum.getText().trim();
        String empName = jTextFieldFPEmpName.getText().trim();
        Date selectedDate = jDateChooser.getDate();

        // Check if fields are empty
        if (empNum.isEmpty() || empName.isEmpty() || selectedDate == null) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate Employee ID (Must be exactly 5 digits)
        if (!empNum.matches("\\d{5}")) {
            JOptionPane.showMessageDialog(this, "Employee Number must be exactly 5 digits!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate Employee Name (Must contain only letters & spaces)
        if (!empName.matches("[a-zA-Z ]+")) {
            JOptionPane.showMessageDialog(this, "Employee Name must contain only letters and spaces!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verify Employee ID & Name from CSV file
        if (!employeeReader.isEmployeeValid(empNum, empName)) {
            JOptionPane.showMessageDialog(this, "Invalid Employee Number or Name! Please enter correct details.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Format date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateOfRequest = sdf.format(selectedDate);

        // Use the correct class to save request
        PasswordResetRequest request = new PasswordResetRequest(empNum, empName, dateOfRequest);
        PasswordResetReader.saveRequest(request);

        JOptionPane.showMessageDialog(this, "Request Sent to IT!", "Success", JOptionPane.INFORMATION_MESSAGE);
        //dispose();
    
    }//GEN-LAST:event_jButtonFPSubmitActionPerformed

    private void jTextFieldFPEmpNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFPEmpNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') { // Allow letters & spaces only
            evt.consume(); // Ignore the key event
        }
    }//GEN-LAST:event_jTextFieldFPEmpNameKeyTyped

    private void jTextFieldFPEmpNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFPEmpNumKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) { // Allow only numbers
            evt.consume(); // Ignore the key event
        }    
    }//GEN-LAST:event_jTextFieldFPEmpNumKeyTyped

    private void jButtonFPCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFPCancelActionPerformed
        Login newClassInstance = new Login();
                 newClassInstance.setVisible(true); 
        dispose();         
    }//GEN-LAST:event_jButtonFPCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton jButtonFPCancel;
    private javax.swing.JButton jButtonFPSubmit;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabelFPDOR;
    private javax.swing.JLabel jLabelFPEmpName;
    private javax.swing.JLabel jLabelFPEmpNum;
    private javax.swing.JLabel jLabelForgotPassword;
    private javax.swing.JLabel jLabelGMT;
    private javax.swing.JLabel jLabelMotor;
    private javax.swing.JLabel jLabelPH;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanelForgotPassword;
    private javax.swing.JPanel jPanelForgotPasswordLabel;
    private javax.swing.JPanel jPanelFormContents;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldFPEmpName;
    private javax.swing.JTextField jTextFieldFPEmpNum;
    // End of variables declaration//GEN-END:variables
}
