package motorph_GUI;

import data_reader9.EmployeeDetailsReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import data_reader9.PasswordResetReader;
import javax.swing.JFrame;
import javax.swing.Timer;
import password_reset9.PasswordResetRequest;

/**
 *
 * @author Four Lugtu
 */

/**
 * Forgot Password Form - Handles password reset requests.
 * 
 * Uses `EmployeeDetailsReader` to validate Employee ID & Name before submission.
 * Ensures Employee Number contains **only numbers** and is **5 digits**.
 * Ensures Employee Name contains **only letters & spaces**.
 * Saves the request if all validations pass.
 */
public class ForgotPasswordForm extends javax.swing.JFrame {
    private Timer timer;
    private EmployeeDetailsReader employeeDetailsReader = new EmployeeDetailsReader("src/data9/Employee.csv", "src/data9/Login.csv");
    
    /**
     * Creates new form ForgotPasswordForm
     */
    
    public ForgotPasswordForm() {
        initComponents();
        this.setResizable(false); // 💡 Prevent resizing
        this.setExtendedState(JFrame.NORMAL);
        setLocationRelativeTo(null); // Center the window
        startClock();
    }
    
    private void startClock() {
        timer = new Timer(1000, e -> updateTimeAndDate());
        timer.start();
    }

    private void updateTimeAndDate() {
        SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm:ss a");
        jLabelTime.setText(timeFormat.format(new Date()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanelForgotPassword = new javax.swing.JPanel();
        jPanelForgotPasswordLabel = new javax.swing.JPanel();
        jLabelForgotPassword = new javax.swing.JLabel();
        jPanelFormContents = new javax.swing.JPanel();
        jLabelFPEmpName = new javax.swing.JLabel();
        jTextFieldFPEmpName = new javax.swing.JTextField();
        jLabelFPEmpNum = new javax.swing.JLabel();
        jTextFieldFPEmpNum = new javax.swing.JTextField();
        jPanelHeader = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabelMotor = new javax.swing.JLabel();
        jLabelPH = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelGMT = new javax.swing.JLabel();
        jButtonFPSubmit = new javax.swing.JButton();
        jButtonFPCancel = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelForgotPassword.setBackground(new java.awt.Color(51, 0, 0));
        jPanelForgotPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelForgotPasswordLabel.setBackground(new java.awt.Color(153, 0, 0));
        jPanelForgotPasswordLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelForgotPassword.setBackground(new java.awt.Color(255, 255, 255));
        jLabelForgotPassword.setFont(new java.awt.Font("Century Gothic", 1, 25)); // NOI18N
        jLabelForgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelForgotPassword.setText("EMPLOYEE FORGOT PASSWORD FORM");
        jPanelForgotPasswordLabel.add(jLabelForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 40));

        jPanelForgotPassword.add(jPanelForgotPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 470, 60));

        jPanelFormContents.setBackground(new java.awt.Color(153, 0, 0));
        jPanelFormContents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFPEmpName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpName.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jLabelFPEmpName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpName.setText("Employee Name:");
        jPanelFormContents.add(jLabelFPEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));
        jPanelFormContents.add(jTextFieldFPEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 260, 30));

        jLabelFPEmpNum.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpNum.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        jLabelFPEmpNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFPEmpNum.setText(" Employee Number:");
        jPanelFormContents.add(jLabelFPEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 70));
        jPanelFormContents.add(jTextFieldFPEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 260, 30));

        jPanelForgotPassword.add(jPanelFormContents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 470, 100));

        jPanelHeader.setBackground(new java.awt.Color(0, 0, 0));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setBackground(new java.awt.Color(0, 0, 102));
        Logo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos9/LogoMPH_(small1).png"))); // NOI18N
        Logo.setText("Username");
        jPanelHeader.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 110));

        jLabelMotor.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelMotor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMotor.setText("MOTOR");
        jPanelHeader.add(jLabelMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 100));

        jLabelPH.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelPH.setForeground(new java.awt.Color(204, 0, 51));
        jLabelPH.setText("PH");
        jPanelHeader.add(jLabelPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, 70, 120));

        jLabelTime.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTime.setText("12:12:12 AM");
        jPanelHeader.add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 170, 32));

        jLabelGMT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelGMT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGMT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGMT.setText("GMT+8 PH Time");
        jPanelHeader.add(jLabelGMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 170, -1));

        jPanelForgotPassword.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 530, 100));

        jButtonFPSubmit.setBackground(new java.awt.Color(251, 0, 54));
        jButtonFPSubmit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonFPSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFPSubmit.setText("SUBMIT");
        jButtonFPSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFPSubmitActionPerformed(evt);
            }
        });
        jPanelForgotPassword.add(jButtonFPSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 170, 40));

        jButtonFPCancel.setBackground(new java.awt.Color(251, 0, 54));
        jButtonFPCancel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonFPCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFPCancel.setText("CANCEL");
        jButtonFPCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFPCancelActionPerformed(evt);
            }
        });
        jPanelForgotPassword.add(jButtonFPCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 170, 40));

        getContentPane().add(jPanelForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButtonFPSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFPSubmitActionPerformed
    /**
    * Handles Forgot Password submission.
    *   Validates Employee ID & Name before allowing submission.
    *   Saves request if validation is successful.
    */
    String empNum = jTextFieldFPEmpNum.getText().trim();
    String empName = jTextFieldFPEmpName.getText().trim();
    Date dateToday = new Date(); // Gets today's date
    SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
    String dateOfRequest = sdf.format(dateToday);
    
    // Check if fields are empty
    if (empNum.isEmpty() || empName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Employee ID (Must be exactly 5 digits)
    if (!empNum.matches("\\d{5}")) {
        JOptionPane.showMessageDialog(this, "Employee Number must be exactly 5 digits!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate Employee Name (Must contain only letters & spaces)
    if (!empName.matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(this, "Employee Name must contain only letters and spaces!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verify Employee ID & Name from CSV file
    if (!employeeDetailsReader.isEmployeeValid(empNum, empName)) {
        JOptionPane.showMessageDialog(this, "Invalid Employee Number or Name! Please enter correct details.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Debugging print 
    System.out.println("Employee Number: " + empNum);
    System.out.println("Employee Name: " + empName);
    System.out.println("Date of Request: " + dateOfRequest);
    
    // Use the correct class to save request
    PasswordResetRequest request = new PasswordResetRequest(empNum, empName, dateOfRequest);

    try {
        PasswordResetReader reader = new PasswordResetReader();
        reader.saveRequest(request);
        JOptionPane.showMessageDialog(this, "Your password reset request has been submitted. A temporary password will be sent to your registered communication method shortly.", "Request Sent to IT!", JOptionPane.INFORMATION_MESSAGE);
        
        // Clear form fields
        jTextFieldFPEmpNum.setText("");
        jTextFieldFPEmpName.setText("");
        
        // Close only ForgotPasswordForm without affecting Login.java
        this.dispose();
        Login newClassInstance = new Login();
                 newClassInstance.setVisible(true);
        dispose();
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving request: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButtonFPSubmitActionPerformed

    private void jButtonFPCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFPCancelActionPerformed
        Login newClassInstance = new Login();
                 newClassInstance.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFPCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton jButtonFPCancel;
    private javax.swing.JButton jButtonFPSubmit;
    private javax.swing.JLabel jLabelFPEmpName;
    private javax.swing.JLabel jLabelFPEmpNum;
    private javax.swing.JLabel jLabelForgotPassword;
    private javax.swing.JLabel jLabelGMT;
    private javax.swing.JLabel jLabelMotor;
    private javax.swing.JLabel jLabelPH;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanelForgotPassword;
    private javax.swing.JPanel jPanelForgotPasswordLabel;
    private javax.swing.JPanel jPanelFormContents;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldFPEmpName;
    private javax.swing.JTextField jTextFieldFPEmpNum;
    // End of variables declaration//GEN-END:variables
}
